[phases.setup]
nixPkgs = ["python3", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-liberation"]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium"
]
